name: AgentMatchPrototype
options:
  bundleIdPrefix: com.agentmatch
settings:
  base:
    SWIFT_VERSION: 5.9
    IPHONEOS_DEPLOYMENT_TARGET: 16.0
targets:
  AgentMatchPrototype:
    type: application
    platform: iOS
    sources:
      - path: AgentMatchPrototype/App/AgentMatchPrototypeApp.swift
        buildPhase: sources
      - path: AgentMatchPrototype/Core/APIClient.swift
        buildPhase: sources
      - path: AgentMatchPrototype/Core/AppTheme.swift
        buildPhase: sources
      - path: AgentMatchPrototype/Core/Models.swift
        buildPhase: sources
      - path: AgentMatchPrototype/ViewModels/HomeViewModel.swift
        buildPhase: sources
      - path: AgentMatchPrototype/Views/HomeView.swift
        buildPhase: sources
      - path: AgentMatchPrototype/Views/QuickAgentView.swift
        buildPhase: sources
      - path: AgentMatchPrototype/Views/CategoryDetailView.swift
        buildPhase: sources
      - path: AgentMatchPrototype/Resources/Assets.xcassets
        buildPhase: resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.agentmatch.prototype
        CODE_SIGN_STYLE: Automatic
        CODE_SIGNING_ALLOWED[sdk=iphonesimulator*]: NO
        CODE_SIGNING_REQUIRED[sdk=iphonesimulator*]: NO
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: NO
        GENERATE_INFOPLIST_FILE: NO
        INFOPLIST_FILE: AgentMatchPrototype/Resources/Info.plist
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    scheme:
      testTargets: []
